import type { Metadata } from "next";
import {  Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
          <Toaster position="top-right" />
      </body>
    </html>
  );
}
